maestros:
    resource: "@MaestrosBundle/Resources/config/routing.yml"
    prefix:   /

costes:
    resource: "@CostesBundle/Resources/config/routing.yml"
    prefix:   /

comun:
    resource: "@ComunBundle/Resources/config/routing.yml"
    prefix:   /
    
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    type: xml

sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation
    prefix:   /sg