#
# ASIGNACIÓN DIRECTA DE CENTROS DE COSTE
#
editAsignacionDirecta:
  path:   /asignacionDirecta/edit/{id}
  defaults: { _controller: CostesBundle:AsignacionDirecta:edit}
addAsignacionDirecta:
  path:   /asignacionDirecta/add
  defaults: { _controller: CostesBundle:AsignacionDirecta:add}
queryAsignacionDirecta:
  path:   /asignacionDirecta/query
  defaults: { _controller: CostesBundle:AsignacionDirecta:query}
#
# EXCEPCIONES A LA ASIGNACIÓN 
#
queryExcepcion:
  path:   /excepcion/query
  defaults: { _controller: CostesBundle:Excepcion:query}
editExcepcion:
  path:   /excepcion/edit/{id}
  defaults: { _controller: CostesBundle:Excepcion:edit}
addExcepcion:
  path:   /excepcion/add/
  defaults: { _controller: CostesBundle:Excepcion:add}
importaExcepcion:
  path:   /excepcion/importar
  defaults: { _controller: CostesBundle:Excepcion:importa}
#
# PLAZAS
#
addPlaza:
  path:   /plaza/add
  defaults: { _controller: CostesBundle:Plaza:add}
editPlaza:
  path:   /plaza/edit/{id}
  defaults: { _controller: CostesBundle:Plaza:edit}
editPlazaByCias:
  path:   /plaza/editbycias/{cias}
  defaults: { _controller: CostesBundle:Plaza:editByCias}
  options:
    expose: true
queryPlaza:
  path:   /plaza/query
  defaults: { _controller: CostesBundle:Plaza:query}
sincroPlaza:
  path:   /plaza/sincro/{id}/{actuacion}/{cias}
  defaults: { _controller: CostesBundle:Plaza:sincro}
  options:
    expose: true
exportarPlaza:
  path:   /plaza/exportar
  defaults: { _controller: CostesBundle:Plaza:exportar}
  options:
    expose: true
ajaxVerTurno:
  path:   /plaza/ajaxverturno/{id}
  defaults: { _controller: CostesBundle:Plaza:ajaxVerTurno}
  options:
    expose: true
ajaxVerUf:
  path:   /plaza/ajaxveruf/{codigo}
  defaults: { _controller: CostesBundle:Plaza:ajaxVerUf}
  options:
    expose: true
ajaxVerPa:
  path:   /plaza/ajaxverpa/{codigo}
  defaults: { _controller: CostesBundle:Plaza:ajaxVerPa}
  options:
    expose: true
ajaxVerUfById:
  path:   /plaza/ajaxverufbyid/{id}
  defaults: { _controller: CostesBundle:Plaza:ajaxVerUfById}
  options:
    expose: true
ajaxVerPaById:
  path:   /plaza/ajaxverpabyid/{id}
  defaults: { _controller: CostesBundle:Plaza:ajaxVerPaById}
  options:
    expose: true
cambioAdscripcion:
  path:   /plaza/cambioadscripcion
  defaults: { _controller: CostesBundle:Plaza:cambioAdscripcion}
  options:
    expose: true
descargaLogPlaza:
  path:   /plaza/descargaLog/{id}
  defaults: { _controller: CostesBundle:Plaza:descargaLog}
  options:
    expose: true
calcularCIAS:
  path:   /plaza/calcularCias/{uf_id}/{catgen_id}
  defaults: { _controller: CostesBundle:Plaza:calcularCias}
  options:
    expose: true
ajaxCalcularCeco:
  path:   /plaza/calcularCeco/{cias}/{uf_id}/{pa_id}
  defaults: { _controller: CostesBundle:Plaza:ajaxCalcularCeco}
  options:
    expose: true
verPlazasByCeco:
  path:   /plaza/verplazasbyceco/{ceco_id}
  defaults: { _controller: CostesBundle:Plaza:verPlazasByCeco}
  options:
    expose: true
amortizacionPlaza:
  path:   /plaza/amortizacion/{id}
  defaults: { _controller: CostesBundle:Plaza:amortizacionPlaza}
  options:
    expose: true
consultarAltas:
  path:   /plaza/consultarAltas/{cias}
  defaults: { _controller: CostesBundle:Plaza:consultaAltas}
  options:
    expose: true
consultarAltasActivas:
  path:   /plaza/consultarAltasActivas/{cias}/{fecha}
  defaults: { _controller: CostesBundle:Plaza:consultaAltasActivas}
  options:
    expose: true

deletePlaza:
  path:   /plaza/delete/{cias}
  defaults: { _controller: CostesBundle:Plaza:delete}
  options:
    expose: true
amortizacionMasiva:
  path:   /plaza/amortiza/masiva
  defaults: { _controller: CostesBundle:Plaza:amortizacionMasiva}
  options:
    expose: true
importaCecoCias:
  path:   /plaza/importaCeco
  defaults: { _controller: CostesBundle:Plaza:importarCeco}
  options:
    expose: true
verPlazasSinCeco:
  path:   /plaza/verplazassinceco
  defaults: { _controller: CostesBundle:Plaza:verPlazasSinCeco}
  options:
    expose: true
cambiarAsignacion:
  path:   /plaza/cambiarAsignacion/{cias}/{nuevoCeco}/{fInicio}/{cecoAnterior_id}
  defaults: { _controller: CostesBundle:Plaza:cambiarAsignacion}
  options:
    expose: true
desAmortizacion:
  path:   /plaza/desAmortizacion/{cias}
  defaults: { _controller: CostesBundle:Plaza:desAmortizacion}
  options:
    expose: true
verCecoCias:
  path:   /plaza/cecocias/query/{plaza_id}
  defaults: { _controller: CostesBundle:Plaza:verCecoCias}
  options:
    expose: true
sincroCecoCias:
  path:   /plaza/cecocias/sincro/{id}
  defaults: { _controller: CostesBundle:Plaza:sincroCecoCias}
  options:
    expose: true
cambiarUnidadOrganizativa:
  path:   /plaza/unidad/cambiar/{cias}/{unidadOrganizativa_id}/{fcCambio}
  defaults: { _controller: CostesBundle:Plaza:cambiarUnidadOrganizativa}
  options:
    expose: true
quitarUnidadOrganizativa:
  path:   /plaza/unidad/quitar/{cias}
  defaults: { _controller: CostesBundle:Plaza:quitarUnidadOrganizativa}
  options:
    expose: true


#
# CECO CENTROS DE COSTE
#
queryCeco:
  path:   /ceco/query
  defaults: { _controller: CostesBundle:Ceco:query}
editCeco:
  path:   /ceco/edit/{id}
  defaults: { _controller: CostesBundle:Ceco:edit}
  options:
    expose: true
deleteCeco:
  path:   /ceco/delete/{ceco_id}
  defaults: { _controller: CostesBundle:Ceco:delete}
  options:
    expose: true
ajaxVerCeco:
  path:   /ceco/ajaxverceco/{id}
  defaults: { _controller: CostesBundle:Ceco:ajaxVerCeco}
  options:
    expose: true
sincroCeco:
  path:   /ceco/sincroCeco/{id}/{actuacion}
  defaults: { _controller: CostesBundle:Ceco:sincro}
addCeco:
  path:   /ceco/add
  defaults: { _controller: CostesBundle:Ceco:add}
importaCeco:
  path:   /ceco/importa
  defaults: { _controller: CostesBundle:Ceco:importa}
descargaLogCeco:
  path:   /ceco/descargaLog/{id}
  defaults: { _controller: CostesBundle:Ceco:descargaLog}
  options:
    expose: true
comprobacionCeco:
  path:   /ceco/comprobacion
  defaults: { _controller: CostesBundle:Ceco:comprobacion}
  options:
    expose: true
#
# UNIDADES FUNCIONALES 
#
editUf:
  path:   /uf/edit/{id}
  defaults: { _controller: CostesBundle:Uf:edit}
  options:
    expose: true
queryUf:
  path:   /uf/query
  defaults: { _controller: CostesBundle:Uf:query}
  options:
    expose: true
verUf:
  path:   /uf/verUf/{id}
  defaults: { _controller: CostesBundle:Uf:verUf}
  options:
    expose: true
addUf:
  path:   /uf/add/
  defaults: { _controller: CostesBundle:Uf:add}
  options:
    expose: true
deleteUf:
  path:   /uf/delete/{id}
  defaults: { _controller: CostesBundle:Uf:delete}
  options:
    expose: true
sincroUf:
  path:   /uf/sincro/{id}/{actuacion}/{equf_id}
  defaults: { _controller: CostesBundle:Uf:sincro}
  options:
    expose: true
descargaLogUf:
  path:   /uf/descargaLog/{id}
  defaults: { _controller: CostesBundle:Uf:descargaLog}
  options:
    expose: true
ajaxCalculaCodigoUf:
  path:   /uf/ajaxCalculaCodigo/{codigo}
  defaults: { _controller: CostesBundle:Uf:ajaxCalculaCodigo}
  options:
    expose: true
queryEqUf:
  path: /uf/equivalencias/query/{uf_id}
  defaults: {_controller: CostesBundle:Uf:queryEqUf}
  options:
    expose: true
activarEqUf:
  path: /uf/equivalencias/activar/{equf_id}
  defaults: {_controller: CostesBundle:Uf:activar}
  options:
    expose: true
desActivarEqUf:
  path: /uf/equivalencias/desactivar/{equf_id}
  defaults: {_controller: CostesBundle:Uf:desActivar}
  options:
    expose: true
#
# PUNTOS ASISTENCIALES 
#
editPa:
  path:   /pa/edit/{id}
  defaults: { _controller: CostesBundle:Pa:edit}
  options:
    expose: true
queryPa:
  path:   /pa/query
  defaults: { _controller: CostesBundle:Pa:query}
  options:
    expose: true
verPa:
  path:   /pa/verPa/{id}
  defaults: { _controller: CostesBundle:Pa:verPa}
  options:
    expose: true
addPa:
  path:   /pa/add/
  defaults: { _controller: CostesBundle:Pa:add}
  options:
    expose: true
deletePa:
  path:   /pa/delete/{id}
  defaults: { _controller: CostesBundle:PA:delete}
  options:
    expose: true
sincroPa:
  path:   /pa/sincro/{id}/{actuacion}/{eqpa_id}
  defaults: { _controller: CostesBundle:Pa:sincro}
  options:
    expose: true
descargaLogPa:
  path:   /pa/descargaLog/{id}
  defaults: { _controller: CostesBundle:Pa:descargaLog}
  options:
    expose: true
queryEqPa:
  path: /pa/equivalencias/query/{pa_id}
  defaults: {_controller: CostesBundle:Pa:queryEqPa}
  options:
    expose: true
activarEqPa:
  path: /pa/equivalencias/activar/{eqpa_id}
  defaults: {_controller: CostesBundle:Pa:activar}
  options:
    expose: true
desActivarEqPa:
  path: /pa/equivalencias/desactivar/{eqpa_id}
  defaults: {_controller: CostesBundle:Pa:desActivar}
  options:
    expose: true
ajaxCalculaCodigoPa:
  path:   /pa/ajaxCalculaCodigo/{codigo}
  defaults: { _controller: CostesBundle:Pa:ajaxCalculaCodigo}
  options:
    expose: true

queryEstructura:
  path: /unidad/query
  defaults: { _controller: CostesBundle:Unidad:queryEstructura}
  options:
    expose: true
ajaxGetEstructura:
  path: /unidad/estructura
  defaults: { _controller: CostesBundle:Unidad:ajaxGetEstructura}
  options:
    expose: true
addUnidad:
  path: /unidad/add
  defaults: { _controller: CostesBundle:Unidad:add}
  options:
    expose: true
editUnidad:
  path: /unidad/edit/{id}
  defaults: { _controller: CostesBundle:Unidad:edit}
  options:
    expose: true
agregarUnidad:
  path: /unidad/agregar/{id}
  defaults: { _controller: CostesBundle:Unidad:agregar}
  options:
    expose: true
agregarPlaza:
  path: /unidad/agregarplaza/{id}
  defaults: { _controller: CostesBundle:Unidad:agregarPlaza}
  options:
    expose: true
deleteUnidad:
  path: /unidad/delete/{id}
  defaults: { _controller: CostesBundle:Unidad:delete}
  options:
    expose: true
ajaxGetUnidad:
  path: /unidad/getunidad/{id}
  defaults: { _controller: CostesBundle:Unidad:ajaxGetUnidad}
  options:
    expose: true
ajaxVerDependencia:
  path: /unidad/dependencia/{id}
  defaults: { _controller: CostesBundle:Unidad:ajaxVerDependencia}
  options:
    expose: true
ajaxVerDependenciaCias:
  path: /unidad/dependenciacias/{cias}
  defaults: { _controller: CostesBundle:Unidad:ajaxVerDependenciaCias}
  options:
    expose: true
ajaxConsultaResposable:
  path: /unidad/responsable/{cias}/{fecha}
  defaults: { _controller: CostesBundle:Unidad:ajaxConsultaResposable}
  options:
    expose: true
imprimirEstructura:
  path: /unidad/estructura/imprimir
  defaults: { _controller: CostesBundle:Unidad:imprimirEstructura}
  options:
    expose: true
cambioResponsable:
  path:   /unidad/cambioResponsable/{unidadOrganizativa_id}/{ciasResponsable}/{fcCambio}
  defaults: { _controller: CostesBundle:Unidad:cambioResponsable}
  options:
    expose: true
agregarValidador:
  path:   /unidad/validador/add/{unidadOrganizativa_id}/{ciasValidador}/{fcCambio}
  defaults: { _controller: CostesBundle:Unidad:addValidador}
  options:
    expose: true
cerrarValidador:
  path:   /unidad/validador/cerrar/{id}
  defaults: { _controller: CostesBundle:Unidad:cerrarValidador}
  options:
    expose: true
deleteValidador:
  path:   /unidad/validador/delete/{id}
  defaults: { _controller: CostesBundle:Unidad:deleteValidador}
  options:
    expose: true
sincroUnidad:
  path:   /unidad/sincro/{id}/{actuacion}
  defaults: { _controller: CostesBundle:Unidad:sincro}
  options:
    expose: true
sincroAsignacion:
  path:   /unidad/sincroAsginacion/{cias}
  defaults: { _controller: CostesBundle:Unidad:sincroAsignacion}
  options:
    expose: true


