app_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index}
#
# SYNCRONIZACIÓN 
#
lanzaSyncro:
    path:   /syncro/lanza
    defaults: { _controller: AppBundle:Syncro:lanza}
    options:
        expose: true
syncroPa:
    path:   /syncro/pa
    defaults: { _controller: AppBundle:Syncro:pa}
    options:
        expose: true
syncroCecos:
    path:   /syncro/cecos
    defaults: { _controller: AppBundle:Syncro:cecos}
    options:
        expose: true
syncroCatGen:
    path:   /syncro/catGen
    defaults: { _controller: AppBundle:Syncro:catGen}
    options:
        expose: true
syncroCateg:
    path:   /syncro/categ
    defaults: { _controller: AppBundle:Syncro:categ}
    options:
        expose: true
syncroCatFp:
    path:   /syncro/catFp
    defaults: { _controller: AppBundle:Syncro:catFp}
    options:
        expose: true
syncroUf:
    path:   /syncro/uf
    defaults: { _controller: AppBundle:Syncro:uf}
    options:
        expose: true
syncroPlazas:
    path:   /syncro/plazas
    defaults: { _controller: AppBundle:Syncro:plazas}
    options:
        expose: true
syncroCecoCias:
    path:   /syncro/cecocias
    defaults: { _controller: AppBundle:Syncro:cecocias}
    options:
        expose: true
syncroTodo:
    path:   /syncro/todo
    defaults: { _controller: AppBundle:Syncro:todo}
    options:
        expose: true
syncroOK:
    path:   /syncro/ok
    defaults: { _controller: AppBundle:Syncro:ok}
    options:
        expose: true
#
# CATEGORIAS PROFESIONALES
#
editCateg:
    path:   /categ/edit/{id}
    defaults: { _controller: AppBundle:Categ:edit}
queryCateg:
    path:   /categ/query
    defaults: { _controller: AppBundle:Categ:query}
addCateg:
    path:   /categ/add/
    defaults: { _controller: AppBundle:Categ:add}
deleteCateg:
    path:   /categ/delete/{id}
    defaults: { _controller: AppBundle:Categ:delete}
    options:
        expose: true
replicaCateg:
    path:   /categ/replica/{id}/{actuacion}
    defaults: { _controller: AppBundle:Categ:replica}
    options:
        expose: true
ajaxCalculaCodigo:
    path:   /categ/calculacodigo/{catgen_id}
    defaults: { _controller: AppBundle:Categ:ajaxCalculaCodigo}
    options:
        expose: true
        
        
queryEqCateg:
    path:   /categ/equivalencias/{categ_id}
    defaults: { _controller: AppBundle:Categ:queryEqCateg}
    options:
        expose: true
activaEqCateg:
    path:   /categ/equivalencias/activa/{id}
    defaults: { _controller: AppBundle:EqCateg:activa}
    options:
        expose: true
desactivaEqCateg:
    path:   /categ/equivalencias/desactiva/{id}
    defaults: { _controller: AppBundle:EqCateg:desactiva}
    options:
        expose: true
addEqCateg:
    path:   /categ/equivalencias/add/{id}
    defaults: { _controller: AppBundle:EqCateg:add}
    options:
        expose: true

#
# CATEGORIAS GENERALES  
#
editCatGen:
    path:   /catgen/edit/{id}
    defaults: { _controller: AppBundle:CatGen:edit}
    options:
        expose: true

queryCatGen:
    path:   /catgen/query
    defaults: { _controller: AppBundle:CatGen:query}
    options:
        expose: true
addCatGen:
    path:   /catgen/add/
    defaults: { _controller: AppBundle:CatGen:add}
deleteCatGen:
    path:   /catgen/delete/{id}
    defaults: { _controller: AppBundle:CatGen:delete}
    options:
        expose: true
replicaCatGen:
    path:   /catgen/replica/{id}/{actuacion}
    defaults: { _controller: AppBundle:CatGen:replica}

 