app_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index}
#
# SYNCRONIZACIÓN 
#
lanzaSyncro:
    path:   /syncro/lanza
    defaults: { _controller: AppBundle:Syncro:lanza}
    options:
        expose: true
syncroPa:
    path:   /syncro/pa
    defaults: { _controller: AppBundle:Syncro:pa}
    options:
        expose: true
syncroCecos:
    path:   /syncro/cecos
    defaults: { _controller: AppBundle:Syncro:cecos}
    options:
        expose: true
syncroCatGen:
    path:   /syncro/catGen
    defaults: { _controller: AppBundle:Syncro:catGen}
    options:
        expose: true
syncroCateg:
    path:   /syncro/categ
    defaults: { _controller: AppBundle:Syncro:categ}
    options:
        expose: true
syncroCatFp:
    path:   /syncro/catFp
    defaults: { _controller: AppBundle:Syncro:catFp}
    options:
        expose: true
syncroUf:
    path:   /syncro/uf
    defaults: { _controller: AppBundle:Syncro:uf}
    options:
        expose: true
syncroPlazas:
    path:   /syncro/plazas
    defaults: { _controller: AppBundle:Syncro:plazas}
    options:
        expose: true
syncroCecoCias:
    path:   /syncro/cecocias
    defaults: { _controller: AppBundle:Syncro:cecocias}
    options:
        expose: true
syncroTodo:
    path:   /syncro/todo
    defaults: { _controller: AppBundle:Syncro:todo}
    options:
        expose: true
syncroOK:
    path:   /syncro/ok
    defaults: { _controller: AppBundle:Syncro:ok}
    options:
        expose: true
