CREATE TABLE ccap.ccap_grc ( 
	id                   int  NOT NULL  AUTO_INCREMENT,
	codigo               varchar(3)  NOT NULL  ,
	descripcion          varchar(25)  NOT NULL  ,
	enuso                varchar(1)  NOT NULL  ,
	CONSTRAINT pk_control_ceco_grc PRIMARY KEY ( id ),
	CONSTRAINT idx001 UNIQUE ( codigo ) 
 );

INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 1, 'A01', 'GERENTE ASISTENCIAL A.P. ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 2, 'A02', 'DIRECTOR GERENTE         ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 3, 'A03', 'GERENTE ADJUNTO          ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 4, 'B04', 'DIR. AGENCIA SANITARIA   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 5, 'B01', 'DIRECTOR ASIST. MEDICO   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 6, 'B02', 'DIRECTOR MEDICO          ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 7, 'B03', 'DIRECTOR TECNICO MEDICO  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 8, 'C01', 'DIRECTOR DE GESTION - A1 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 9, 'C02', 'DIRECTOR TECNICO - A1    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 10, 'C03', 'DIRECTOR DE GESTION - A2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 11, 'C04', 'DIRECTOR TECNICO - A2    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 12, 'C05', 'SUBDIRECTOR MEDICO       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 13, 'D01', 'DIRECTOR ASIST. ENFERMERO', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 14, 'D02', 'DIRECTOR DE ENFERMERIA   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 15, 'D03', 'DIRECTOR TEC. ENFERMERIA ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 16, 'D04', 'SUBDIRECTOR TECNICO - A1 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 17, 'D05', 'SUBDIRECTOR TECNICO - A2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 18, 'D06', 'SUBDIRECTOR GESTION - A1 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 19, 'D07', 'SUBDIRECTOR GESTION - A2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 20, 'E01', 'SUBDIRECTOR ENFERMERIA   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 21, 'F01', 'JEFE SERVICIO NIVEL 29   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 22, 'G01', 'JEFE SERVICIO FAC. P.R.L.', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 23, 'G02', 'MEDICO AGENCIA SANITARIA ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 24, 'G03', 'MEDICO FAMILIA NIVEL 28  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 25, 'H01', 'JEFE SECCION FAC. FAR. H.', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 26, 'H02', 'COORD. DE UNIDAD DOCENTE ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 27, 'H03', 'DIRECTOR CENTRO TIPO I   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 28, 'H04', 'DIRECTOR CENTRO TIPO II  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 29, 'H05', 'DIRECTOR CENTRO TIPO III ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 30, 'H06', 'COORD. EQUIPOS AP        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 31, 'H07', 'COORD. EQUIPOS AP (APD)  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 32, 'H08', 'COORD. EQUIPOS AP (DOC.) ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 33, 'H09', 'COORD. EQUIPOS AP (ESAD) ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 34, 'H10', 'COORDINADOR MEDICO DE APD', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 35, 'H11', 'COORD. MEDICO EAP        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 36, 'H12', 'COORD. MEDICO SAR        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 37, 'H13', 'COORD. MEDICO SUAP       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 38, 'H14', 'COORD. SALUD BUCODENTAL  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 39, 'H15', 'COORDINADOR APD          ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 40, 'H16', 'COORD. EQUIPOS AP (SUAP) ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 41, 'H17', 'COORD. EQUIPOS AP (UAC)  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 42, 'I01', 'ADJUNTO                  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 43, 'I02', 'BECARIO PROYECTO REDES   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 44, 'I03', 'F.E. CENTRO SANDOVAL     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 45, 'I04', 'F.E.A.                   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 46, 'I05', 'FARMACEUTICO             ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 47, 'I06', 'MEDICO CASA DE SOCORRO   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 48, 'I07', 'MEDICO DE APD            ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 49, 'I08', 'MEDICO APOYO A C.S.      ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 50, 'I09', 'MEDICO DE COLABORADORA   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 51, 'I10', 'MEDICO DE CUPO           ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 52, 'I11', 'MEDICO CUPO PEQ. ESP.    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 53, 'I12', 'MEDICO DE ESADP          ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 54, 'I13', 'MEDICO DE FAMILIA DE AP  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 55, 'I14', 'MEDICO FAMILIA - PEDIATRA', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 56, 'I15', 'MEDICO DE FAMILIA LABORAL', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 57, 'I16', 'MEDICO DE S.A.R          ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 58, 'I17', 'MEDICO SAR EVENTUAL      ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 59, 'I18', 'MEDICO DE S.U.A.P.       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 60, 'I19', 'MEDICO REFUERZO          ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 61, 'I20', 'MEDICO SINDROME TOXICO   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 62, 'I21', 'ODONTOLOGO               ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 63, 'I22', 'ODONTOLOGO 2 Z.B.        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 64, 'I23', 'ODONTOLOGO 3 Z.B.        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 65, 'I24', 'ODONTOLOGO DE CUPO       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 66, 'I25', 'ODONTOLOGO +3 Z.B.       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 67, 'I26', 'PEDIATRA DE AP           ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 68, 'I27', 'PEDIATRA DE AREA         ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 69, 'I28', 'PEDIATRA AREA 2 Z.B.     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 70, 'I29', 'PEDIATRA AREA 3 Z.B.     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 71, 'I30', 'PEDIATRA AREA +3 Z.B.    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 72, 'I31', 'PEDIATRA DE COLABORADORA ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 73, 'I32', 'PEDIATRA DE CUPO         ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 74, 'I33', 'PSICOLOGO                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 75, 'I34', 'PSICOLOGO CLINICO        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 76, 'I35', 'PSICOLOGO CLINICO 2 Z.B. ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 77, 'I36', 'PSICOLOGO CLINICO 3 Z.B. ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 78, 'I37', 'PSICOLOGO CLINICO +3 Z.B.', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 79, 'I38', 'PSIQUIATRA USM           ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 80, 'I39', 'TECNICO DE SALUD PUBLICA ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 81, 'I90', 'M.I.R.                   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 82, 'I91', 'M.I.R. 1º                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 83, 'I92', 'M.I.R. 2º                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 84, 'I93', 'M.I.R. 3º                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 85, 'I94', 'M.I.R. 4º                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 86, 'I95', 'FACULT. LABORAL NIVEL 9  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 87, 'I98', 'FACULTATIVO EXCESO SAR   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 88, 'I99', 'FACULTATIVO DOBLAJE      ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 89, 'J01', 'RESP. ENF. EQUIPOS AP    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 90, 'J02', 'RESP ENFERMERIA EN C.S.  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 91, 'J03', 'RESP. ENF. CENTRO S. APD ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 92, 'J04', 'RESP. ENF. EQUIPOS AP APD', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 93, 'K01', 'ENFERMERO/A ESPECIALISTA ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 94, 'K02', 'MATRONA                  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 95, 'K03', 'MATRONA 1 Z.B.           ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 96, 'K04', 'MATRONA 1 Z.B. T1        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 97, 'K05', 'MATRONA 1 Z.B. T2        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 98, 'K06', 'MATRONA 1 Z.B. T3        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 99, 'K07', 'MATRONA 1 Z.B. T4        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 100, 'K08', 'MATRONA 2 Z.B.           ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 101, 'K09', 'MATRONA 2 Z.B. T1        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 102, 'K10', 'MATRONA 2 Z.B. T2        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 103, 'K11', 'MATRONA 2 Z.B. T3        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 104, 'K12', 'MATRONA 2 Z.B. T4        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 105, 'K13', 'MATRONA 3 Z.B.           ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 106, 'K14', 'MATRONA 3 Z.B. T1        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 107, 'K15', 'MATRONA 3 Z.B. T2        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 108, 'K16', 'MATRONA 3 Z.B. T3        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 109, 'K17', 'MATRONA 3 Z.B. T4        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 110, 'K18', 'MATRONA DE APD           ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 111, 'K19', 'MATRONA DE CUPO          ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 112, 'L01', 'ENFERMERO APOYO A A.P.   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 113, 'L02', 'ENFERMERO/A  S.A.R.      ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 114, 'L03', 'ENFERMERO SAR EVENTUAL   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 115, 'L04', 'ENFERMERO/A A.P.         ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 116, 'L05', 'ENFERMERO/A A.P. (36H)   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 117, 'L06', 'ENFERMERO CASA SOCORRO   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 118, 'L07', 'ENFERMERO/A DE APD       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 119, 'L08', 'ENFERMERO APOYO A C.S.   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 120, 'L09', 'ENFERMERO COLABORADORA   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 121, 'L10', 'ENFERMERO/A DE ESADP     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 122, 'L11', 'ENFERMERO/A DE ZONA      ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 123, 'L12', 'ENFERMERO/A EN CONSULTAS ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 124, 'L13', 'ENFERMERO CONSULTAS 36H  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 125, 'L14', 'ENFERMERO SERV. CENTRALES', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 126, 'L15', 'ENFERMERO/A JEFE/ADJUNTA ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 127, 'L16', 'ENFERMERO/A REFUERZO     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 128, 'L17', 'ENFERMERO/A S.U.A.P.     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 129, 'L18', 'FISIOTERAPEUTA           ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 130, 'L19', 'FISIOTERAPEUTA 1 Z.B.    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 131, 'L20', 'FISIOTERAPEUTA 1 Z.B. T1 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 132, 'L21', 'FISIOTERAPEUTA 1 Z.B. T2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 133, 'L22', 'FISIOTERAPEUTA 1 Z.B. T3 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 134, 'L23', 'FISIOTERAPEUTA 1 Z.B. T4 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 135, 'L24', 'FISIOTERAPEUTA 2 Z.B.    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 136, 'L25', 'FISIOTERAPEUTA 2 Z.B. T1 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 137, 'L26', 'FISIOTERAPEUTA 2 Z.B. T2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 138, 'L27', 'FISIOTERAPEUTA 2 Z.B. T3 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 139, 'L28', 'FISIOTERAPEUTA 2 Z.B. T4 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 140, 'L29', 'FISIOTERAPEUTA 3 Z.B.    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 141, 'L30', 'FISIOTERAPEUTA 3 Z.B. T1 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 142, 'L31', 'FISIOTERAPEUTA 3 Z.B. T2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 143, 'L32', 'FISIOTERAPEUTA 3 Z.B. T3 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 144, 'L33', 'FISIOTERAPEUTA 3 Z.B. T4 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 145, 'L34', 'TRABAJADOR SOCIAL        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 146, 'L35', 'TRABAJADOR SOCIAL G.1    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 147, 'L36', 'TRABAJADOR SOCIAL G.1 T1 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 148, 'L37', 'TRABAJADOR SOCIAL G.1 T2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 149, 'L38', 'TRABAJADOR SOCIAL G.1 T3 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 150, 'L39', 'TRABAJADOR SOCIAL G.2    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 151, 'L40', 'TRABAJADOR SOCIAL G.2 T1 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 152, 'L41', 'TRABAJADOR SOCIAL G.2 T2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 153, 'L42', 'TRABAJADOR SOCIAL G.2 T3 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 154, 'L43', 'TRABAJADOR SOCIAL G.3    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 155, 'L44', 'TRABAJADOR SOCIAL G.3 T1 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 156, 'L45', 'TRABAJADOR SOCIAL G.3 T2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 157, 'L46', 'TRABAJADOR SOCIAL G.3 T3 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 158, 'L47', 'TRABAJADOR SOCIAL G.4    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 159, 'L48', 'TRABAJADOR SOCIAL G.4 T1 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 160, 'L49', 'TRABAJADOR SOCIAL G.4 T2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 161, 'L50', 'TRABAJADOR SOCIAL G.4 T3 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 162, 'L90', 'E.I.R.                   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 163, 'L91', 'E.I.R. 1º                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 164, 'L92', 'E.I.R. 2º                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 165, 'L93', 'SANITARIO LABORAL NIVEL 7', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 166, 'M01', 'T.S.E. LABORATORIO       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 167, 'M02', 'T.S.E. RADIODIAGNOSTICO  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 168, 'M03', 'T.S.E. HIGIENE BUCODENTAL', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 169, 'M04', 'TCAE FUNCIONES TEC. ESP. ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 170, 'N01', 'TCAE                     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 171, 'N02', 'TCAE (36H)               ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 172, 'N03', 'TCAE DE ESADP            ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 173, 'N04', 'TCAE EN CONSULTAS        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 174, 'N05', 'TCAE EN CONSULTAS (36H)  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 175, 'O01', 'JEFE DE SERVICIO - A1    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 176, 'O02', 'JEFE DE SERVICIO - A2    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 177, 'O03', 'JEFE DE SECCION - A1     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 178, 'O04', 'JEFE DE SECCION - A2     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 179, 'O05', 'JEFE DE SECCION - C1     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 180, 'P01', 'GRUPO TECNICO F.A.       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 181, 'P02', 'INGENIERO ARQ. SUPERIOR  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 182, 'P03', 'PER. TECNICO TIT. SUP.   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 183, 'P04', 'TEC. SUP. SIST. Y T.I.   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 184, 'Q01', 'JEFE DE GRUPO - A2       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 185, 'Q02', 'GRUPO GESTION F.A.       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 186, 'Q03', 'INGENIERO ARQ. TECNICO   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 187, 'Q04', 'INGENIERO TECNICO J.G.   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 188, 'Q05', 'PER. TECNICO GRADO MEDIO ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 189, 'Q06', 'TEC. GES. SIST. Y T.I.   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 190, 'R01', 'JEFE DE GRUPO - C1       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 191, 'R02', 'JEFE DE GRUPO - C2       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 192, 'R03', 'JEFE DE GRUPO - E        ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 193, 'S01', 'GOBERNANTA               ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 194, 'T01', 'ENCARGADO EQ. PER. OFICIO', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 195, 'T02', 'GRUPO ADMINISTRATIVO F.A.', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 196, 'T03', 'JEFE DE EQUIPO - C1      ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 197, 'T04', 'JEFE DE EQUIPO - C2      ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 198, 'T05', 'PERS. TECNICO NO TITULADO', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 199, 'T06', 'TECNICO URG. Y EME. - C2 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 200, 'T07', 'TECNICO URG. Y EME. - E  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 201, 'T08', 'TEC. ESP. SIST. Y T.I.   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 202, 'T09', 'TELEFONISTA ENCARGADA H. ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 203, 'U01', 'JEFE PER. SUBALTERNO - C2', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 204, 'U02', 'JEFE PER. SUBALTERNO - E ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 205, 'V01', 'ALBAÑIL                  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 206, 'V02', 'AUX. ADM. OPERADOR E.M.  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 207, 'V03', 'AUX. ADM. OP. EQUIPO MEC.', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 208, 'V04', 'AUXILIAR ADMINISTRATIVO  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 209, 'V05', 'AUXILIAR DE FARMACIA     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 210, 'V06', 'AZAFATA - REL. PUBLICAS  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 211, 'V07', 'CALEFACTOR               ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 212, 'V08', 'CARPINTERO               ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 213, 'V09', 'CONDUCTOR                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 214, 'V10', 'CONDUCTOR INSTALACIONES  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 215, 'V11', 'CONDUCTOR VEHICULO ESP-  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 216, 'V12', 'CONDUCTOR ENCARGADO P.M. ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 217, 'V13', 'COSTURERA                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 218, 'V14', 'ELECTRICISTA             ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 219, 'V15', 'FONTANERO                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 220, 'V16', 'FOTOGRAFO                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 221, 'V17', 'JARDINERO                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 222, 'V18', 'LOCUTOR                  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 223, 'V19', 'MECANICO                 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 224, 'V20', 'MONITOR                  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 225, 'V21', 'OPERADOR MAQUINA IMPRIMIR', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 226, 'V22', 'PELUQUERO                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 227, 'V23', 'PERSONAL DE OFICIO       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 228, 'V24', 'PINTOR                   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 229, 'V25', 'TAPICERO                 ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 230, 'V26', 'TELEFONISTA              ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 231, 'W01', 'CELADOR AUX. AUTOPSIAS   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 232, 'W02', 'CELADOR CON ASIS. DIRECTA', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 233, 'W03', 'CELADOR DE SAR           ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 234, 'W04', 'CELADOR DE SUAP          ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 235, 'W05', 'CELADOR EN ANIMALARIO    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 236, 'W06', 'CELADOR BLOQUE QUIRURGICO', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 237, 'W07', 'CELADOR ENC. TUR. C/ASIS.', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 238, 'W08', 'CELADOR REFUERZO         ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 239, 'W09', 'CELADOR TURNO AUX. AUT.  ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 240, 'W10', 'CELADOR TURNO C/ATENCION ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 241, 'W11', 'CELADOR TURNO ANIMALARIO ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 242, 'W12', 'CELADOR TURNO QUIRURGICO ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 243, 'W13', 'CELADOR TURNO ET. C/ASIS.', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 244, 'X01', 'CELADOR ENCARGDO LAV.    ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 245, 'X02', 'CELADOR ENC. TUR. ALMACEN', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 246, 'X03', 'CELADOR SIN ASIS. DIRECTA', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 247, 'X04', 'LAVANDERA                ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 248, 'X05', 'LIMPIADORA               ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 249, 'X06', 'PEON                     ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 250, 'X07', 'PINCHE                   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 251, 'X08', 'PLANCHADORA              ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 252, 'Z98', 'SIN NOMINA               ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 253, 'Z99', 'COMPLEMENTO DE PENSION   ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 254, 'ZZZ', 'NO DEFINIDO              ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 255, 'I40', 'F_MEDICO APOYO A LOS C.S.', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 256, 'A04', 'GERENTE ADJUNTO A2       ', 'S' ); 
INSERT INTO ccap.ccap_grc( id, codigo, descripcion, enuso ) VALUES ( 257, 'I41', 'FACULT ESPEC MED TRABAJO ', 'S' ); 
