CREATE TABLE ccap.ccap_catfp ( 
	id                   int  NOT NULL  AUTO_INCREMENT,
	codigo               varchar(4)    ,
	descripcion          varchar(40)    ,
	enuso                varchar(1)    ,
	CONSTRAINT pk_control_ceco_catfp PRIMARY KEY ( id ),
	CONSTRAINT idx001 UNIQUE ( codigo ) 
 );

INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 0, '2008', 'GERENTE ADJUNTO          ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 1, '2204', 'DIRECTOR ASISTENCIAL MEDI', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 2, '2407', 'DIRECTOR TECNICO MEDICO  ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 3, '2408', 'DIRECTOR TECNICO         ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 4, '2411', 'SUBDIRECTOR TECNICO      ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 5, '2607', 'DIRECTOR TECNICO DE ENFER', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 6, '2704', 'DIRECTOR ASISTENCIAL DE E', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 7, '2818', 'DIRECTOR DE CENTRO DE SAL', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 8, '3001', 'DIRECTOR GERENTE         ', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 9, '3101', 'DIRECTOR MEDICO          ', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 10, '3201', 'DIRECTOR GESTION Y SS.GG.', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 11, '3301', 'DIRECTOR ENFERMERIA      ', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 12, '3401', 'COORDINADOR EQUIPOS A.P. ', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 13, '3402', 'RESPONSABLE ENFERMERIA AP', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 14, '3403', 'COORD. U. SALUD BUCODENTA', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 15, '3405', 'TECNICO SALUD PUBLICA    ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 16, '3406', 'COORDINADOR UNIDAD DOCENT', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 17, '4001', 'JEFE DE SERVICIO NS      ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 18, '4002', 'JEFE DE SECCION NS       ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 19, '4003', 'JEFE DE GRUPO            ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 20, '4004', 'JEFE DE EQUIPO           ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 21, '5101', 'MEDICO DE FAMILA E.A.P.  ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 22, '5102', 'PEDIATRA DE E.A.P.       ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 23, '5103', 'ODONTOESTOMATOLOGO       ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 24, '5104', 'ODONTOLOGO CUPO          ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 25, '5105', 'MEDICO DE FAMILIA DE CUPO', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 26, '5106', 'PEDIATRA DE CUPO         ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 27, '5107', 'MEDICO DE S.N.U.         ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 28, '5108', 'MEDICO DE S.E.U.         ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 29, '5109', 'FARMACEUTICO             ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 30, '5110', 'PEDIATRA DE AREA         ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 31, '5111', 'MEDICO SUAP/SAR          ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 32, '5112', 'MEDICO ESAD              ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 33, '5113', 'MEDICO DE SAR            ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 34, '5114', 'MEDICO DE APOYO A CENTROS', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 35, '5115', 'F.E.A.                   ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 36, '5203', 'MEDICO RESIDENTE         ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 37, '6002', 'ENFERMERA/O CUPO         ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 38, '6003', 'ENFERMERA/O_AP           ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 39, '6004', 'ENFERMERA/O S.N.U.       ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 40, '6005', 'ENFERMERA/O S.E.U.       ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 41, '6006', 'ENFERMERA/O SUAP/SAR     ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 42, '6007', 'ENFERMERA/O ESAD         ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 43, '6008', 'ENFERMERO/A SAR          ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 44, '6010', 'ENFERMERA/O (APOYO)      ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 45, '6011', 'ENFERMERAS DE APOYO A C.S', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 46, '6016', 'ENFERMERA/O (A. SISTEMA) ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 47, '6102', 'MATRONA DE AREA          ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 48, '6103', 'MATRONA DE CUPO          ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 49, '6111', 'MATRONA DE  APD          ', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 50, '6202', 'FISIOTERAPEUTA           ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 51, '6402', 'T.E. LABORATORIO         ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 52, '6404', 'T.E. RADIODIAGNOSTICO    ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 53, '6410', 'HIGIENISTA DENTAL        ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 54, '6501', 'AUX. ENFERMERIA ANTIGUO S', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 55, '6502', 'AUX. ENFERMERIA DE E.A.P.', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 56, '6510', 'AUX. ENFERMERIA DE APOYO ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 57, '6517', 'AUX. ENFERMERIA ESAD     ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 58, '6604', 'A.T.S. JEFE              ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 59, '6605', 'ENFERMERA ADJUNTA        ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 60, '6701', 'TECNICO GRUPO A          ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 61, '7002', 'GRUPO TECNICO DE LA F.A. ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 62, '7006', 'PSICOLOGO                ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 63, '7007', 'PSICOLOGO CLINICO        ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 64, '7012', 'OTRO PERSONAL DE GRUPO A ', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 65, '7041', 'TECNICO SUP. DE SIST. Y T', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 66, '7101', 'INGENIEROS TECNICOS      ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 67, '7102', 'GRUPO GESTION DE LA F.A. ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 68, '7107', 'TRABAJADOR SOCIAL        ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 69, '7109', 'TECNICO DE GES. DE SIST. ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 70, '7205', 'GRUPO ADMINISTRATIVO     ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 71, '7232', 'TEC. ESPECIALIST DE SIST.', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 72, '7302', 'GRUPO AUXILIAR ADMINISTRA', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 73, '7304', 'CALEFACTOR               ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 74, '7305', 'CARPINTERO               ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 75, '7306', 'CONDUCTOR                ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 76, '7307', 'COSTURERA                ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 77, '7308', 'ELECTRICISTA             ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 78, '7309', 'FONTANERO                ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 79, '7312', 'JARDINERO                ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 80, '7314', 'MECANICO                 ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 81, '7320', 'TELEFONISTA              ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 82, '7327', 'GRUPO AUXILIAR ADM. EAP  ', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 83, '7335', 'JEFE DE PERSONAL SUBALTE ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 84, '7402', 'LAVANDERA                ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 85, '7403', 'LIMPIADORA               ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 86, '7406', 'PLANCHADORA              ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 87, '7407', 'CELADOR                  ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 88, '7408', 'CELADOR DE E.A.P.        ', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 89, '8101', 'MEDICO A.P.D. INTEGRADO  ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 90, '8102', 'MEDICO A.P.D. NO INTEGRA ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 91, '8201', 'A.T.S. A.P.D. INTEGRADO  ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 92, '8202', 'A.T.S. A.P.D. NO INTEGRAD', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 93, '8301', 'MATRONA A.P.D.           ', 'S' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 94, '9998', 'COMPLEMENTO DE PENSION   ', 'N' ); 
INSERT INTO ccap.ccap_catfp( id, codigo, descripcion, enuso ) VALUES ( 95, '9999', 'NO DEFINIDA              ', 'N' ); 
