#
# login
#
login:
    path: /login
    defaults: { _controller: ComunBundle:Login:login}
login_check:
    path: /login_check
    defaults: { _controller: ComunBundle:Login:check }    
logout:
    path:     /login/logout
    defaults: { _controller: ComunBundle:Login:logout }    
    options:
        expose: true
 #
 # GESTION DE USUARIOS
 #
cambioPassword:
    path:   /usuario/cambioPassword/{id}
    defaults: { _controller: ComunBundle:Usuario:CambioPassword}
    options:
        expose: true
queryUsuario:
    path:   /usuario/query
    defaults: { _controller: ComunBundle:Usuario:query}
    options:
        expose: true
addUsuario:
    path:   /usuario/add
    defaults: { _controller: ComunBundle:Usuario:add}
    options:
        expose: true
editUsuario:
    path:   /usuario/edit/{id}
    defaults: { _controller: ComunBundle:Usuario:edit}
    options:
        expose: true
deleteUsuario:
    path:   /usuario/delete/{id} 
    defaults: { _controller: ComunBundle:Usuario:delete}
    options:
        expose: true
#
# BASES DE DATOS 
#
queryBaseDatos:
    path:   /basedatos/query
    defaults: { _controller: ComunBundle:BaseDatos:query}
    options:
        expose: true
editBaseDatos:
    path:   /basedatos/edit/{id}
    defaults: { _controller: ComunBundle:BaseDatos:edit}
addBaseDatos:
    path:   /basedatos/add
    defaults: { _controller: ComunBundle:BaseDatos:add}
#
# CARGAS MASIVAS MEDIANTE FICHEROS 
#
descargaLogFichero:
    path:   /cargafichero/descargaLog/{id}
    defaults: { _controller: ComunBundle:CargaFichero:descargaLog}
    options:
        expose: true

queryCargaFichero:
    path:   /cargafichero/query
    defaults: { _controller: ComunBundle:CargaFichero:query}
    options:
        expose: true
#
# CARGA INICIAL DE TABLAS
#
queryCargaInicial:
    path:   /cargainicial/query
    defaults: { _controller: ComunBundle:CargaInicial:query}
    options:
        expose: true
addCargaInicial:
    path:   /cargainicial/add
    defaults: { _controller: ComunBundle:CargaInicial:add}
    options:
        expose: true
descargaLog:
    path: /cargainicial/descarga/{id}
    defaults: { _controller: ComunBundle:CargaInicial:descargaLog}
    options:
        expose: true
limpiarCargaInicial:
    path:   /cargainicial/limpia/{id}
    defaults: { _controller: ComunBundle:CargaInicial:limpia}
    options:
        expose: true

lanzaCargaInicial:
    path:   /cargainicial/lanza/{id}
    defaults: { _controller: ComunBundle:CargaInicial:lanza}
    options:
        expose: true

queryDependencia:
    path: /cargainicial/dependencia/query/{cargaInicial_id}
    defaults: { _controller: ComunBundle:CargaInicial:queryDependencia}    
    options:
        expose: true
addDependencia:
    path: /cargainicial/dependencia/add/{cargaInicial_id}
    defaults: { _controller: ComunBundle:CargaInicial:addDependencia}    
    options:
        expose: true
deleteDependencia:
    path: /cargainicial/dependencia/delete/{id}
    defaults: { _controller: ComunBundle:CargaInicial:deleteDependencia}    
    options:
        expose: true

querySincroLog:
    path: /sincrolog/query
    defaults: { _controller: ComunBundle:SincroLog:query}
    options:
        expose: true
descargaSincroLog:
    path: /sincrolog/descarga/{id}
    defaults: { _controller: ComunBundle:SincroLog:descarga}
    options:
        expose: true
